//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ketsTable
    {
        public int ID { get; set; }   
        [Required(ErrorMessage="Required")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Required")]
        public int Salary { get; set; }
        [Required(ErrorMessage = "Required")]
        public int Age { get; set; }                                                                                                                                                        
        [Required(ErrorMessage = "Required")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Required")]
        public string Department { get; set; }
    }
}
